dev:
  schedule: False
  kv_store:
    sample_parent_flow_process_date: "2020-02-10"
qa:
  schedule: False
  kv_store:
    sample_parent_flow_process_date: "2020-02-10"
prod:
  schedule: True
  kv_store:
    sample_parent_flow_process_date: "2020-02-10"
